name: Build and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    if: ${{ false }} # disable for now
    runs-on: macos-latest
    name: Build macOS

    steps:
      - name: Check out Source
        uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Build macOS
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: "Telemetry Viewer.xcodeproj"
          scheme: "Telemetry Viewer (macOS)"
          destination: platform=macOS
          action: build
      - name: Build iOS
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: "Telemetry Viewer.xcodeproj"
          scheme: "Telemetry Viewer (iOS)"
          destination: platform=iOS
          action: build
  SwiftLint:
    runs-on: ubuntu-latest
    name: SwiftLint
    steps:
      - uses: actions/checkout@v1
      - uses: norio-nomura/action-swiftlint@3.2.1
